---
- name: Criar snapshot da VM windows10 no Hyper-V
  hosts: hyperv_host
  tasks:
    - name: Criar checkpoint da VM windows10
      ansible.windows.win_powershell:
        script: |
          $vmName = "windows10"
          $snapshotName = "Snapshot-$(Get-Date -Format 'yyyy-MM-dd-HH-mm-ss')"
          Checkpoint-VM -Name $vmName -SnapshotName $snapshotName
          Write-Output "Snapshot criado: $snapshotName"
      register: checkpoint_result

    - name: Exibir resultado do snapshot
      ansible.builtin.debug:
        msg: "{{ checkpoint_result.output }}"
