---
- name: Criar arquivo com data, hostname e IP público no Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Testar conexão WinRM
      ansible.windows.win_command: whoami
      register: winrm_test
      failed_when: false

    - name: Exibir resultado do teste
      ansible.builtin.debug:
        msg: "Teste WinRM: {{ winrm_test.stdout }}"
      when: winrm_test.rc == 0

    - name: Obter a data atual
      ansible.windows.win_command: powershell -Command "Get-Date -Format 'yyyy-MM-dd'"
      register: current_date

    - name: Obter o hostname da máquina
      ansible.windows.win_command: hostname
      register: hostname_output

    - name: Obter o IP público da máquina
      ansible.windows.win_uri:
        url: https://api.ipify.org
        return_content: yes
      register: public_ip

    - name: Criar o arquivo arquivo-teste.txt com as informações
      ansible.windows.win_copy:
        content: |
          Data: {{ current_date.stdout }}
          Hostname: {{ hostname_output.stdout }}
          IP Público: {{ public_ip.content }}
        dest: C:\Users\tsuna\Desktop\arquivo-teste.txt
